DROP TABLE IF EXISTS `T_MESSAGE`;
CREATE TABLE `T_MESSAGE` (
  `ID` int(18) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `VERSION` int(9) NOT NULL COMMENT '乐观锁版本',
  `TYPE` tinyint(1) NOT NULL COMMENT '消息类型，1 qq消息；2 短信',
  `DESTINATION` varchar(255) NOT NULL COMMENT '发送目的地',
  `MESSAGE` varchar(255) NOT NULL COMMENT '内容',
  `STATUS` tinyint(1) NOT NULL COMMENT '状态 1 未发送；2 发送中；3 发送成功；4 发送失败',
  `CREATEDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `FINISHDATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;
