spring:
  application:
    name: message-sender-service
    version: 1.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 50
      query-timeout: 21600

management:
  endpoints:
    shutdown:
      enabled: false
    health:
      enabled: true

mybatis:
  type-handlers-package: com.john.model.typehandler